services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app:delegated
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - SECRET_KEY=dev-secret-key-change-in-production
      - DATABASE_URL=mysql+pymysql://user:password@db:3306/personalsite_dev
      - PYTHONPATH=/app
    depends_on:
      - db
    networks:
      - app-network
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  website:
    build:
      context: ./website
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./website:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - NODE_ENV=development
      - NUXT_TELEMETRY_DISABLED=1
      - API_URL=http://api:8000
      - PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    networks:
      - app-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
      - /app/.nuxt
    environment:
      - NODE_ENV=development
      - NUXT_TELEMETRY_DISABLED=1
      - API_URL=http://api:8000
    networks:
      - app-network
    depends_on:
      - api
    stdin_open: true
    tty: true
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: personalsite_dev
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_dev_data:

networks:
  app-network:
    driver: bridge
