"""add cpc table

Revision ID: 7ee957419436
Revises: dc0ce899a259
Create Date: 2025-09-05 23:03:25.353763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee957419436'
down_revision = 'dc0ce899a259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpc_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_type', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('topics', sa.Text(), nullable=False),
    sa.Column('key_learning_outcomes', sa.Text(), nullable=False),
    sa.Column('points', sa.INTEGER(), nullable=False),
    sa.Column('practice_change', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cpc_items')
    # ### end Alembic commands ###
