"""remove published_at column from users

Revision ID: dc0ce899a259
Revises: 731b91768204
Create Date: 2025-09-02 22:42:57.865512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc0ce899a259'
down_revision = '731b91768204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'published_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('published_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
